---
- name: Start ngrok tunnel for Gitea
  hosts: localhost
  connection: local
  tasks:
    - name: Run ngrok to expose port 3000
      shell: ngrok http 3000
      async: 3600
      poll: 0
      register: ngrok_tunnel

    - name: Display ngrok tunnel status (manual check needed)
      debug:
        msg: "✅ ngrok should now be running and forwarding to http://localhost:3000. Visit the public URL shown in the terminal (e.g., https://26dc15a26c40.ngrok-free.app/)"
